### ISSUE TITLE
De aanvullende modules zijn duidelijk met BOMOS verbonden maar hebben een eigen governance

### ISSUE THREAD

**Issue by isik001** [Logius-standaarden/BOMOS-LinkedData#11]
### Soort

- [ ] Tekstuele fout
- [X] Verbetersuggestie
- [X] Onduidelijke tekst

### Omschrijving

De aanvullende modules zijn duidelijk met BOMOS verbonden maar hebben een eigen governance daarom worden de modules; “Stelsels en Linked Data” aangevuld met een korte tekst dat ze een eigen governance hebben met een verwijzing naar BOMOS. | 

### Naam

Güldeniz Isik 

### Email

guldeniz.ozdemirisik@logius.nl

### Organisatie

Logius

**Comment by isik001** [comment]
@WvandenBerg of @edwinwisse, wie pakt dit op? kan het zijn dat dit nog niet is opgepkat? ik kan namelijk geen korte tekst vinden dat de modules een eigen governance hebben.

**Comment by isik001** [comment]
voor beide modules deze tekst aangevuld: De aanvullende modules zijn nauw verbonden met BOMOS en hebben tegelijkertijd een eigen governancestructuur. Zo wordt er binnen de context van het bredere BOMOS-kader duidelijk gemaakt dat de genoemde modules hun eigen governancestructuur hebben. Dit biedt transparantie en verduidelijking aan de betrokken partijen en stakeholders, zodat zij begrijpen dat hoewel er een verbinding bestaat met BOMOS, deze modules afzonderlijk worden beheerd en bestuurd.

**Comment by isik001** [comment]
beide modules volgend tekst toegevoegd: De aanvullende modules zijn nauw verbonden met BOMOS en hebben tegelijkertijd een eigen governancestructuur. Zo wordt er binnen de context van het bredere BOMOS-kader duidelijk gemaakt dat de genoemde modules hun eigen governancestructuur hebben. Dit biedt transparantie en verduidelijking aan de betrokken partijen en stakeholders, zodat zij begrijpen dat hoewel er een verbinding bestaat met BOMOS, deze modules afzonderlijk worden beheerd en bestuurd.

**Comment by isik001** [comment]
Voor beide modules volgende tekst toegevoegd: De aanvullende modules zijn nauw verbonden met BOMOS en hebben tegelijkertijd een eigen governancestructuur. Zo wordt er binnen de context van het bredere BOMOS-kader duidelijk gemaakt dat de genoemde modules hun eigen governancestructuur hebben. Dit biedt transparantie en verduidelijking aan de betrokken partijen en stakeholders, zodat zij begrijpen dat hoewel er een verbinding bestaat met BOMOS, deze modules afzonderlijk worden beheerd en bestuurd.

**Comment by wisze** [comment]
Gesloten, besproken en goedgekeurd in klankbord 26-6-2023

**Comment by wisze** [comment]
Gesloten, besproken en goedgekeurd in klankbord 26-6-2023
