### ISSUE TITLE
Link naar VocBench is dode link

### ISSUE THREAD

**Issue by JosVanderArend** [Logius-standaarden/BOMOS-LinkedData#9]
### Soort

- [ ] Tekstuele fout
- [ ] Verbetersuggestie
- [ ] Onduidelijke tekst

### Omschrijving

In paragraaf 10.1 staat een tabel van hulpmiddelen. De link van VocBench werkt niet; de werkende link lijkt nu te zijn: https://ec.europa.eu/isa2/vocbench-semantic-technologies-data-management_en/

### Naam

Jos van der Arend

### Email

j.vanderarend@kennisnet.nl

### Organisatie

Kennisnet

**Comment by edwinwisse** [comment]
Dit toont weer duidelijk de noodzaak van persistent URLs. 
De pagina waar de voorgestelde URL naar verwijst bevat zelf ook weer een melding dat dit een gearchiveerde pagina is. Met het aflopen van het ISA2 programma zijn alle links daaronder niet heel toekomstvast meer. Zou onderstaande link niet beter zijn?
https://op.europa.eu/en/web/eu-vocabularies/vocbench
Deze heeft isa2 niet meer in het pad staan.

**Comment by isik001** [comment]
Link aangepast naar  https://op.europa.eu/en/web/eu-vocabularies/vocbench

**Comment by isik001** [comment]
bij beide modules deze tekst toegevoegd; De aanvullende modules zijn nauw verbonden met BOMOS en hebben tegelijkertijd een eigen governancestructuur. Zo wordt er binnen de context van het bredere BOMOS-kader duidelijk gemaakt dat de genoemde modules hun eigen governancestructuur hebben. Dit biedt transparantie en verduidelijking aan de betrokken partijen en stakeholders, zodat zij begrijpen dat hoewel er een verbinding bestaat met BOMOS, deze modules afzonderlijk worden beheerd en bestuurd.
